### ISSUE TITLE
How to handle page not found issue

### ISSUE THREAD

**Issue by parthkdas** [xsanisty/SlimStarter#13]
I want to handle the requests for which routing rules are not set and giving page not found message.
Instead I want to display custom page not found page or redirect to some other page.

**Comment by ikhsan017** [comment]
Hi @parthkdas 
You can try to put this in the beginning of the routes.php file

```php
App::notFound(function(){
    View::display('404.twig');
});
```

**Comment by parthkdas** [comment]
Thnx . Its working
